version: '3.9'

services:
  reverse-proxy:
    container_name: reverse-proxy
    depends_on:
      - backend
      - frontend
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.prod
    container_name: frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.prod
    container_name: backend
    ports:
      - 3080:3080
    restart: on-failure
