version: '3.9'

services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile.dev
    container_name: finance-db
    environment:
      - POSTGRES_PASSWORD=123
      - REMOTE_API_KEY=dbebd4e0-86b3-4bb0-9026-8354c3346f9b
      - REMOTE_DB_NAME=xwyksyfg
    ports:
      - 5432:5432
    restart: always
