version: '3.9'

services:
  db:
    build:
      args:
        - LOCAL_DB_NAME=finance
        - POSTGRES_PASSWORD=123
        - REMOTE_API_KEY=dbebd4e0-86b3-4bb0-9026-8354c3346f9b
        - REMOTE_DB_NAME=xwyksyfg
      context: .
      dockerfile: ./db/Dockerfile.dev
    container_name: finance-db
    environment:
      - POSTGRES_PASSWORD=123
      - REMOTE_API_KEY=dbebd4e0-86b3-4bb0-9026-8354c3346f9b
      - REMOTE_DB_NAME=xwyksyfg
    ports:
      - 5432:5432
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    container_name: finance-backend
    depends_on:
      - db
    environment:
      - BACKEND_PORT=3080
      - JWT_SECRET=secret
      - LOCAL_DB_NAME=finance
      - MODE=dev
      - POSTGRES_PASSWORD=123
    ports:
      - 3080:3080
    restart: on-failure
