version: '3.9'

services:
  reverse-proxy:
    container_name: reverse-proxy
    depends_on:
      - client
      - server
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    container_name: client
    depends_on:
      - server
    ports:
      - 3000:3000
    restart: on-failure

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile.server
    container_name: server
    ports:
      - 3080:3080
    restart: on-failure
