version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: finances-frontend
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - ./:/var/app/
