version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: finance-backend
    depends_on:
      - db
    env_file:
      - ./config/dev.env
    ports:
      - '3080:3080'
    restart: always
    volumes:
      - ./backend:/app # Named volume for all files.
      - /app/node_modules # Anonymous volume for node_modules only to fix issue with bcrypt.

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: finance-frontend
    depends_on:
      - backend
    env_file:
      - ./config/dev.env
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.dev
    container_name: finance-db
    env_file:
      - ./config/dev.env
    ports:
      - '5432:5432'
    restart: always
