version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./server/Dockerfile.dev
    container_name: finance-backend
    depends_on:
      - db
    env_file:
      - ./config/dev.env
    ports:
      - '3080:3080'
    restart: always

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile.dev
    container_name: finance-db
    env_file:
      - ./config/dev.env
    ports:
      - '5432:5432'
    restart: always
