version: "3.9"

services:
  reverse-proxy:
    container_name: reverse-proxy
    depends_on:
      - finance-client
    image: nginx:latest
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  finance-client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    container_name: finance-client
    ports:
      - 3000:3000
    restart: on-failure

  finance-server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    container_name: finance-server
    ports:
      - 3080:3080
    restart: on-failure
