name: Deploy to surge.sh

on:
  push:
    branches:
      - master

jobs:
  deploy-to-surge:
    name: Deploy to surge.sh
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.13.0"
      - name: Installing node modules
        run: npm install
      - name: Building app
        run: npm run build
      - name: Deploy to https://my-budgets.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "https://my-budgets.surge.sh"
          project: "./dist"
          login: ${{ secrets.SURGE_EMAIL }}
          token: ${{ secrets.SURGE_TOKEN }}
