name: TypeScript checks, build and tests
on: [push]
jobs:
  ts-checks-build-and-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.13.0"
      - name: Installing node modules
        run: npm install
      - name: Checking for TypeScript errors
        run: npm run check-types
      - name: Building app
        run: npm run build
      - name: Running components tests
        run: npm run test:component
      - name: Clonning server app repository
        run: git clone https://github.com/aleksandr-kiliushin/personal-app-server.git ./server-app
      - name: Installing server app packages
        run: npm --prefix ./server-app install
      - name: Creating SERVER_DEV_ENV_FILE for backend and DB
        run: echo "${{ secrets.SERVER_DEV_ENV_FILE }}" > ./server-app/dev.env
      - name: Starting server app for tests
        run: npm --prefix ./server-app run dev:db-and-api -- --detach
      - name: Wait for DB to be initialized
        run: sleep 30s
      - name: TEMP Executing e2e tests for server app
        run: npm --prefix ./server-app run test
      # - name: Running components tests
      #   run: npm run test:e2e
